name: Build and push DocsGPT Docker image with releases

on:
  release:
    types: [published]

jobs:

  deploy:
    if: github.repository == 'anasKhafaga/DocsGPT'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: check
        run: |
          echo "${{ secrets.DOCKER_USERNAME }}/docsgpt:${{ github.event.release.tag_name }},${{ secrets.DOCKER_USERNAME }}/docsgpt:latest"
          echo ${{secrets.DOCKER_USERNAME}}
          echo ${{ github.event.release.tag_name }}

      - name: Build and push Docker images to docker.io and ghcr.io
        uses: docker/build-push-action@v4
        with:
          file: './application/Dockerfile'
          platforms: linux/amd64
          context: ./application
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/docsgpt:${{ github.event.release.tag_name }},${{ secrets.DOCKER_USERNAME }}/docsgpt:latest
